### ISSUE TITLE
Failing tests - strange numerical behavior

### ISSUE THREAD

**Issue by ratiotile** [nim-lang/c2nim#159]
Win7, Nim 0.20.0 i386. Compiled with: `nim cpp --run testsuite\tester.nim`

Seems that hexadecimals all become 0.

2 tests fail on master: 
enum.c:4-10 `	car = 0x10,
	truck,
	boat = 0x01,
	ship = 1,
	speedboat = 1,
	bicycle = 4,
	bobycar`
enum.nim:3 
`boat = 0x00000001, bicycle = 4, bobycar, car = 0x00000010, truck` *expected*
`boat = 0x00000000, bicycle = 4, bobycar, car = 0x00000000, truck`

systest.c:136 `#define MASK(x) ((x) & 0xff)` results in:
systest.nim:108 `  ((x) and 0x000000FF)` *expected* vs `  ((x) and 0x00000000)`

**Comment by dxxb** [comment]
I'm seeing the same issue with c2nim 51c9eaf (current master HEAD) using Nim 0.20.0 on Ubuntu 16.04 i686.

All non decimal integer constants seem to be affected (octal and binary too) and c2nim lexer doesn't seem to be the problem because it parses them fine and assigning the right base to tokens. It looks like the issue occurs when rendering the AST but I do not know enough about Nim internals to guess what it could be and cannot investigate further right now.

The issue does not occur on an x64 system.

**Comment by Araq** [comment]
Cannot reproduce.
