### ISSUE TITLE
Error: ';' expected on GNU-EFI header files

### ISSUE THREAD

**Issue by Immortalin** [nim-lang/c2nim#75]
Error: `/builds/gnu-efi-3.0.4/inc/efi.h(31, 1) Error: ';' expected`

```C
#define EFI_FIRMWARE_VENDOR         L"INTEL" // line 30
#define EFI_FIRMWARE_MAJOR_REVISION 12   // line 31
#define EFI_FIRMWARE_MINOR_REVISION 33
#define EFI_FIRMWARE_REVISION ((EFI_FIRMWARE_MAJOR_REVISION <<16) | (EFI_FIRMWARE_MINOR_REVISION))
```

**Comment by Immortalin** [comment]
You can find the libraries [here](https://launchpad.net/ubuntu/+source/gnu-efi) and the source [here](https://sourceforge.net/projects/gnu-efi/).

**Comment by rosshadden** [comment]
@Immortalin I had a similar problem, and it was fixed by removing comments.  In your case, `// line 30` and `// line 31`.

You may have added those just for context for this issue post, which would mean it's not your problem.  If so, it might be the spacing before `L"INTEL"`, so try removing that.  Also try inserting a newline before line 31, which I also found to help fix that error in some cases.
